version: '3.8'

services:
  app:
    build: .
    container_name: design_patterns
    restart: no
    ports:
      - "3000:3000"
      - "9229:9229"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: ["yarn", "start:debug"]